baseURL = 'https://skeltongate.homes'
languageCode = 'en-gb'
title = 'Skelton Gate Community'
images = ['/img/og-image.jpg']
buildDrafts = false
enableGitInfo = true

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"

# ICS calendar feed output format
[mediaTypes."text/calendar"]
  suffixes = ["ics"]

[outputFormats.calendar]
  name = "calendar"
  baseName = "calendar"
  mediaType = "text/calendar"
  isPlainText = true
  notAlternative = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
